### PR TITLE
Add all `[extras]` as outputs, add update script, maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- fixes #19

Notes:
- adds `strawberry-graphql-with-X` where `X` is something found in the upstream `pyproject.toml`
- check the current recipe vs the `pyproject.toml`
- promptly delete the `pyproject.toml` and use the generated `setup.py`
- adapted from https://github.com/conda-forge/spacy-models-feedstock
- the script was _originally_ intended to be used locally, a la
  ```bash
  python recipe/update_recipe.py
  ``` 
  - needs `tomli` and `jinja2`
- adds self as maintainer :wave:

Backwards-incompatible changes:
- this leaves the core `strawberry-graphql` _very_ lightweight, and could _theoretically_ break a downstream
  - but the only one I see is `fastberry`, which declares its own deps on `fastapi`, etc.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/strawberry-graphql ready for review

**Comment by thewchan** [comment]
@bollwyvl thanks for all the work! There's a lot of technique you used in this recipe that I'm not familiar with, are there documentation about them, in case others need to come in and help with the recipe?

**Comment by bollwyvl** [comment]
Here's some stuff for:
- [multiple outputs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section)
  - [matplotlib-feedstock](https://github.com/conda-forge/matplotlib-feedstock) is probably the original, widely-used multi-output feedstock
  - [dagster-feedstock](https://github.com/conda-forge/dagster-feedstock) is  "hand-written"  one
- [pin_subpackage](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#conda-build-specific-jinja2-functions) and friends

The rest is pretty far off-rails, in terms of the templating, and really only [spacy-models-feedstock](https://github.com/conda-forge/spacy-models-feedstock/) is anything like it.

**Pull request merged**
